[general]
	live_config_reload= true
import = [
    "/home/katsar/.config/alacritty/themes/themes/nordic.toml"
]
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
blur = true

[font]
size = 14.0

[font.normal]

family = 'Hack Nerd Font Propo'
style = 'Regular'

