     
live_config_reload= true

import = [
    "/Users/macbook/.config/alacritty/alacritty-theme/themes/dracula.toml"
]

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
blur = true

[font]
size = 14.0

[font.normal]

family = 'Hack Nerd Font Propo'
style = 'Regular'

