general.live_config_reload= true

general.import = [
    "/Users/diaolos/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
blur = false

[font]
size = 22.0

[font.normal]
family = 'Hack Nerd Font Propo'
style = 'Regular'
