set -g default-terminal "screen-256color"
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v 
unbind r
bind r source-file ~/.config/.tmux.conf

#unbind for neovim
unbind C-\\    # Disable Ctrl+\
#Resizing panels
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5 
bind -r h resize-pane -L 5

bind -r m resize-pane -Z
bind -r f run-shell "tmux neww ~/github/scripts/tmux-sessionizer.sh"
set-window-option -g mode-keys vi
# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Ensure window index numbers get reordered on delete.
set-option -g renumber-windows on
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g detach-on-destroy off
bind-key -T copy-mode-vi v  send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi C-v send -X rectangle-toggle  # make block visual mode
bind-key -T copy-mode-vi y send -X copy-selection # copy text with "y"

# Spotify Player w/ `spotify_player`
bind -r P run-shell '
if [ "#{session_name}" = "spotify" ]; then
  tmux display-message "Already in spotify session - use prefix d to detach"
else
  tmux has-session -t spotify 2>/dev/null || tmux new-session -d -s spotify spotify_player
  tmux display-popup -E "tmux attach -t spotify"
fi'
# Session jumping with `fzf`
bind C-j display-popup -E "~/github/scripts/session-fzf.sh"
# kill session
bind k display-popup -E "\
    tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
    fzf --reverse -m --header=kill-session |\
    xargs -I {} tmux kill-session -t {}"

set -g mouse on
# tpm plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
# set -g @plugin 'catppuccin/tmux#v2.3.0' # See https://github.com/catppuccin/tmux/tags for additional tags
# set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
# To update plugin for future revisions or bug fixes, do the "Prefix + U" keycombo
set -g @plugin 'sainnhe/tmux-fzf'
# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl

set -g @plugin 'tmux-plugins/tmux-yank'


set -g @plugin 'tmux-plugins/tmux-sensible'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
